=== raml-apis/SalesforceChatter/schemas/createGroupInTheOrganizationRequest-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "announcement" : {
      "type" : "string" ,
      "required" : false
    } ,
    "canHaveChatterGuests" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "information" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "text" : {
          "type" : "string" ,
          "required" : false
        } ,
        "title" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "isArchived" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isAutoArchiveDisabled" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "owner" : {
      "type" : "string" ,
      "required" : false
    } ,
    "visibility" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/SalesforceChatter/examples/createGroupInTheOrganizationRequest-example.json
{
   "announcement" : "0D5D0000000K4XT",
   "canHaveChatterGuests" : "true",
   "description" : "This group is building a powerful API.",
   "information" : {
      "text" : "Read this section before you post to the group.",
      "title" : "Information"
   },
   "isArchived" : "false",
   "isAutoArchiveDisabled" : "false",
   "name" : "Chatter API",
   "owner" : "00590000000DmPw",
   "visibility" : "PublicAccess"
}
